# Generated by Django 6.0.2 on 2026-05-12 19:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="counted_views",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="created_date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="published_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="status",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="updated_date",
            field=models.DateField(auto_now=True),
        ),
    ]
