# Generated by Django 6.0.4 on 2026-05-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_alter_post_options_post_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(default="default.png", upload_to="blog/"),
        ),
    ]
