# Generated by Django 6.0.2 on 2026-05-19 15:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"ordering": ["created_date"]},
        ),
    ]
